# Generated by Django 5.0.7 on 2024-10-10 08:58

import Admin_app.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coupons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('discount', models.IntegerField()),
                ('max_amount', models.IntegerField()),
                ('profile', models.ImageField(max_length=250, upload_to=Admin_app.models.upload_coupon_image)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2024, 10, 10, 8, 58, 28, 113032, tzinfo=datetime.timezone.utc))),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('status', models.BooleanField(default=False)),
            ],
        ),
    ]
