# Generated by Django 5.0.7 on 2024-10-10 08:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupons',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
