# Generated by Django 5.0.7 on 2024-08-11 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='driverlocation',
            old_name='latitude',
            new_name='location',
        ),
        migrations.RemoveField(
            model_name='driverlocation',
            name='longitude',
        ),
    ]
