# Generated by Django 5.0.7 on 2024-08-11 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_app', '0002_rename_latitude_driverlocation_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverlocation',
            name='location',
            field=models.CharField(max_length=250),
        ),
    ]
