# Generated by Django 5.0.7 on 2024-08-15 09:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_app', '0003_alter_driverlocation_location'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TripDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=250)),
                ('destination', models.CharField(max_length=250)),
                ('distance', models.CharField(max_length=10)),
                ('duration', models.CharField(max_length=10)),
                ('amount', models.IntegerField()),
                ('orderId', models.IntegerField()),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Trip_driver', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Trip_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
