# Generated by Django 5.0.7 on 2024-08-15 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_app', '0004_tripdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='tripdetails',
            name='tripOTP',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
    ]
