# Generated by Django 5.0.7 on 2024-08-15 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_app', '0006_alter_tripdetails_orderid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tripdetails',
            name='tripOTP',
            field=models.CharField(max_length=10),
        ),
    ]
