# Generated by Django 5.0.7 on 2024-08-15 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_app', '0007_alter_tripdetails_tripotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='tripdetails',
            name='status',
            field=models.CharField(default=None, max_length=20),
            preserve_default=False,
        ),
    ]
