# Generated by Django 5.0.7 on 2024-08-15 11:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_app', '0008_tripdetails_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='tripdetails',
            name='dataTime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
