# Generated by Django 5.0.7 on 2024-08-29 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_app', '0010_alter_tripdetails_distance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tripdetails',
            name='payment_type',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
