# Generated by Django 5.0.7 on 2024-08-31 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_app', '0011_tripdetails_payment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tripdetails',
            name='amount',
            field=models.IntegerField(blank=True),
        ),
    ]
