# Generated by Django 5.0.7 on 2024-09-02 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_app', '0012_alter_tripdetails_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tripdetails',
            name='amount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
