# Generated by Django 5.0.7 on 2024-09-04 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_app', '0014_userwallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='userwallet',
            name='status',
            field=models.CharField(default='add', max_length=50),
            preserve_default=False,
        ),
    ]
