# Generated by Django 5.0.7 on 2024-09-09 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User_app', '0016_tripdetails_service_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tripdetails',
            old_name='dataTime',
            new_name='dateTime',
        ),
    ]
