# Generated by Django 5.0.7 on 2024-09-11 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_app', '0017_rename_datatime_tripdetails_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='tripdetails',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tripdetails',
            name='rating',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
