# Generated by Django 5.0.7 on 2024-09-19 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_app', '0018_tripdetails_message_tripdetails_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverlocation',
            name='user_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
