# Generated by Django 5.0.7 on 2024-09-19 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_app', '0019_driverlocation_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverlocation',
            name='location',
            field=models.JSONField(),
        ),
    ]
