# Generated by Django 5.0.7 on 2024-07-26 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='address',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='role',
        ),
    ]
