# Generated by Django 5.0.7 on 2024-07-28 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication_app', '0002_remove_customuser_address_remove_customuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverdata',
            name='comments',
            field=models.TextField(default='No comments provided'),
        ),
        migrations.AddField(
            model_name='driverdata',
            name='dicline_reason',
            field=models.CharField(default='No reason provided', max_length=150),
        ),
        migrations.AddField(
            model_name='driverdata',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
