# Generated by Django 5.0.7 on 2024-07-30 06:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication_app', '0003_driverdata_comments_driverdata_dicline_reason_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='driverdata',
            old_name='status',
            new_name='request',
        ),
        migrations.AlterField(
            model_name='driverdata',
            name='customuser',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
