# Generated by Django 5.0.7 on 2024-08-07 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication_app', '0004_rename_status_driverdata_request_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverdata',
            name='current_Status',
            field=models.BooleanField(default=False),
        ),
    ]
