# Generated by Django 5.0.7 on 2024-08-30 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication_app', '0005_driverdata_current_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='ride',
            field=models.BooleanField(default=False),
        ),
    ]
