# Generated by Django 5.0.7 on 2024-09-04 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication_app', '0006_customuser_ride'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='wallet',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
