# Generated by Django 5.0.7 on 2024-09-16 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication_app', '0007_customuser_wallet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
