# Generated by Django 5.0.7 on 2024-09-17 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication_app', '0008_alter_customuser_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverdata',
            name='Vehicle_type',
            field=models.CharField(choices=[('Bike', 'Bike'), ('Car', 'Car'), ('Auto', 'Auto')], default='Car', max_length=20, null=True),
        ),
    ]
