# Generated by Django 5.0.7 on 2024-09-17 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication_app', '0009_driverdata_vehicle_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverdata',
            name='Vehicle_type',
            field=models.CharField(choices=[('Bike', 'Bike'), ('Car', 'Car'), ('Auto', 'Auto')], default='Car', max_length=20),
            preserve_default=False,
        ),
    ]
